version: '3'

services:
  simpo-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    volumes:
      - shared-data:/data

  simpo-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - shared-data:/data
    privileged: true  # This is required to modify iptables rules

volumes:
  shared-data:
