version: '3'

services:
  simpo-frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    volumes:
      - shared-data:/data
    environment:
      OPENID_CLIENT_ID: ""
      OPENID_CLIENT_SECRET: ""
      OPENID_ISSUER: ""
      OPENID_SESSION_SECRET: ""
      OPENID_SCOPE: "openid profile email"
      OPENID_CALLBACK_URL: "/oauth/openid/callback"
      OPENID_BUTTON_LABEL: ""
      OPENID_IMAGE_URL: ""

  simpo-backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    volumes:
      - shared-data:/data
    privileged: true  # This is required to modify iptables rules

volumes:
  shared-data:
