version: '3'

services:
  simpo-frontend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.frontend
    volumes:
      - shared-data:/data

  simpo-backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.backend
    volumes:
      - shared-data:/data
    privileged: true  # This is required to modify iptables rules

volumes:
  shared-data:
